version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/London
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: "@types/google-apps-script"
    versions:
    - 1.0.22
    - 1.0.23
    - 1.0.24
    - 1.0.25
    - 1.0.26
    - 1.0.27
    - 1.0.28
    - 1.0.29
    - 1.0.30
  - dependency-name: lodash
    versions:
    - 4.17.20
