version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "$CLASP_KEY1" > ~/.clasprc.json
      - run: sudo npm i @google/clasp -g

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run: clasp versions

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      
      - run: rm -rf node_modules
      - run: clasp push
